language: python
git:
  depth: 9999999
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install pybuilder
  - pip install coveralls
  - pip install sh
  - pyb install_dependencies

script: "pyb verify analyze"
after_success:
  - coveralls --verbose
before_deploy:
  - pyb package
deploy:
  provider: pypi
  user: Immobilienscout24
  distributions: "sdist"
  skip_cleanup: true
  password:
    secure: b96A+7B+hPYzHErMAt3AgT0tdrz9OEeShVCFxGJ9gUJ5qMigNN8Ayyj+5uKz0VQcIonti1Y7froUG/YPxZUQy0BGyQI1OJQH2Ba0vh1HatnBLFBmHvMI8YMIUh+SFtg1d9co+Rxy9LjOY/i42FDOG5Xv5i1+xS4ouPu+EHArXimKenPv+7uX3vbN0rbUrTsNKP6KjZvL7c72LJ0FLM4E0g5mmZKlznci8bvNwnVThXYSoc0kmteq0NeQav4mS4gpgxaXNwdBF9bq2XCbK7UyUhZDNBsbEYM1dMYdThdA4uU0p1DPowz9ls/nLuyALU3ueki2Y1OyiKHftVZFc1fuNRHeA0nFzk41aTDvrHHb4DD/mzDh74edb6CUM7Lhj5zuph3eG4ngDPI7YBVM1f6hwjLF1Fg0XRamreYDhCFhrniQ6PF2VoTovBNPdk8vbaKUKPSzwTGwI79G4YsBLL2tjLnL7XjhAoHBEScu8EX0xhEQVgOxQViTtBnjNUJnsB5g6FjmFof3QJ8cpk/CJ7UWdTNghCnO9RBfHKYPhOu3fNCVIfdCyCSTCTMJ3kp9a95A36YjeFCKvtWFnaKeU82KK51ptZtbDsHU2IPxhi1qwT6rktzcJ0rr6Q2G34MaeAksy9j1BK0dv33sWWHvYvD5lHwhb47ygExFXgbLSNXPT7M=
  on:
    repo: ImmobilienScout24/pybuilder_aws_lambda_plugin
    python: '3.5'
    branch: master
